### ISSUE TITLE
Throwing error " … is not valid under any of the given schemas - 'input' "

### ISSUE THREAD

**Issue by apkawel** [kevincure/YourPersonalAI#1]
First, thank you for this! I'm excited to use it and contribute if I can.

I'm a noob but I'm hoping you can point me in the right direction to get this up and running. I'm trying to load up some appellate-court opinions to summarize them and ask questions about their content.

I've set up the files as described. In the "Documents" folder, I placed about 100 PDFs. But when I run `Embeddings.py`, I see this:

[blob of text from the PDFs]`] is not valid under any of the given schemas - 'input'`

I imagine there is a "first part" of the error message before the blob of text starts, but my terminal output won't let me scroll back that far (it starts the blob of text somewhere in the middle).

Despite the error, I ran `app.py` and then `index.html` but after entering a question I only see the message `An error occurred while processing your request.`

I'm pretty sure this is because `Embeddings.py` isn't running all the way through.

Any ideas about what is going on, or where I could go to educate myself to fix the problem? Thanks for any help you might offer.

**Comment by kevincure** [comment]
Look at the textchunks.csv file and see whether your pdfs scanned.
Alternatively, run embeddings with just one pdf to test.

**Comment by apkawel** [comment]
Problem seems to be solved.

As far as I can tell, the issue may have been one of three things: either (1) the number of PDFs was too great; (2) one of the PDFs was somehow incorrectly formatted or corrupt; or (3) it was too much information to throw at the OpenAI free trial.

I tried running with just 1 PDF and it worked fine — amazingly well, in fact! You're a wizard. 

I then tried it with about 30 PDFs and the `Embeddings.py` operation did not complete because of a server error ("too many requests, try again later" or something like that). I figured that that might have been caused because I was still on the free trial, so I upgraded to the paid plan; threw 50 PDFs at it, and it still works. But when I tried throwing 73 or more documents at it, I got the same error as before. But the 73rd document that it stops on will import just fine by itself. 

Perhaps there is a limit on the amount of information it can handle at once? I imagine, though, that I could run `Embeddings.py` on two groups of documents and then just combine the .csv files. Still, that's an issue I'd like to try to find a solution to.

After importing the 50 documents, the results from prompts asking for an overall summary of the documents ("What are these documents about?" "What court are these documents from?" [they were all from the same court] etc.) were not useful, but that's kinda the name of the game and just something that needs to get worked out / improved.

Nevertheless, thank you so much! I'm pretty astounded at how well this works. I'm going to try to teach myself more about this field to try to either contribute to your project or fork it into something else. Much appreciated!

**Comment by kevincure** [comment]
Thanks.

On your q's - yes, I imagine there may be limits to the embedding on OpenAI.

On summaries, this definitely won't work. Just think through how the idea
works here - you find the eight chunks of text most similar to the chunk of
text in the query, then have GPT search those chunks for the answer to the
query.  Summarizing 20 long document in this way is of course impossible.
That said, asking direct questions about specific papers is absolutely
possible (see an example in the last tweet in my thread on this).
Hopefully it continues to be useful - and I'm sure we'll have commercial
products doing even crazier versions of this soon.

Kevin
